baseURL = 'https://rodrigofreire.pages.dev/'
locale = 'pt-br'
title = 'Rodrigo Freire - Blog de Pesquisa e Desenvolvimento em Deep Tech'
copyright = '© 2026 Rodrigo Freire Desenvolvedor e Pesquisador em Deep Tech'
theme = 'PaperMod'

[params]
  author = 'Rodrigo'
  description = 'Pesquisas em Segurança da Informação, Engenharia Reversa e Cloud Security.'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = true
  defaultTheme = 'auto'

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'monokai'
  tabWidth = 4
